---

- name: OCI | Get the namespace
  oracle.oci.oci_object_storage_namespace_facts:
    compartment_id: "{{ os_mirror_to_oci.compartment_id }}"
  register: _objns

- name: OCI | Create bucket
  oracle.oci.oci_object_storage_bucket:
    state: present
    compartment_id: "{{ os_mirror_to_oci.compartment_id }}"
    name: "{{ os_mirror_to_oci.bucket }}"
    namespace_name: "{{ _objns.namespace }}"

- name:  OCI | Show Summary of OS Mirroring
  ansible.builtin.debug:
    msg:
    - "Bucket/image object: {{ os_mirror_to_oci.bucket }}/{{ cluster_state.compute.image_id }}"
    - "Image name: {{ cluster_state.compute.image_id }}"
  when: not(_st_image.stat.exists)

- name: OCI | Upload image to bucket
  oracle.oci.oci_object_storage_object:
    namespace_name: "{{ _objns.namespace }}"
    bucket_name: "{{ os_mirror_to_oci.bucket }}"
    object_name: "{{ cluster_state.compute.image_id }}"
    src: "{{ collection_bin_dir + '/' +  cluster_state.compute.image_id }}"
    force: false
  register: _upload

- name: OCI | Creating Custom Image
  oracle.oci.oci_compute_image:
    compartment_id: "{{ os_mirror_to_oci.compartment_id }}"
    image_source_details:
      bucket_name: "{{ os_mirror_to_oci.bucket }}"
      namespace_name: "{{ _objns.namespace }}"
      object_name: "{{ cluster_state.compute.image_id }}"
      source_type: objectStorageTuple
      source_image_type: "{{ os_mirror_to_oci.image_type }}"
    launch_mode: PARAVIRTUALIZED
    display_name: "{{ cluster_state.compute.image_id }}"
  register: _custom_image

- name: OCI | Get global image capability schemas
  oracle.oci.oci_compute_global_image_capability_schema_facts:
    display_name: OCI.ComputeGlobalImageCapabilitySchema
  register: _global_image_capability_schemas

- name: OCI | Set global schema as fact
  ansible.builtin.set_fact:
    _global_image_capability_schema: "{{ _global_image_capability_schemas.compute_global_image_capability_schemas | first }}"

- name: OCI | Get global image capability schema versions
  oracle.oci.oci_compute_global_image_capability_schema_version_facts:
    compute_global_image_capability_schema_version_name: "{{ _global_image_capability_schema.current_version_name }}"
    compute_global_image_capability_schema_id: "{{ _global_image_capability_schema.id }}"
  register: _compute_global_image_capability_schema_versions

- name: OCI | Set schema version as fact
  ansible.builtin.set_fact:
    _image_capability_schema: "{{ (_compute_global_image_capability_schema_versions.compute_global_image_capability_schema_versions | first).schema_data }}"

- name: OCI | Update source from GLOBAL to IMAGE in schema
  ansible.builtin.set_fact:
    _image_capability_schema: "{{ _image_capability_schema | combine(source_image_patch, recursive=True) }}"
  vars:
    source_image_patch: "{ '{{ item.key }}': { 'source': 'IMAGE' } }"
  with_dict: "{{ _image_capability_schema }}"

- name: OCI | Patch image capability schema
  ansible.builtin.set_fact:
    _image_capability_schema: "{{ _image_capability_schema | combine(oci.image_capability_schema_patch, recursive=True) }}"

- name: OCI | Image capability applied on custom image
  ansible.builtin.debug:
    var: _image_capability_schema

- name: OCI | Update image capabilities on custom image
  oracle.oci.oci_compute_image_capability_schema:
    state: present
    compartment_id: "{{ os_mirror_to_oci.compartment_id }}"
    compute_global_image_capability_schema_version_name: "{{ _global_image_capability_schema.current_version_name }}"
    image_id: "{{ _custom_image.image.id }}"
    schema_data: "{{ _image_capability_schema }}"
