---
- debug: var=bin_oc

- name: get pod sha
  ansible.builtin.shell: |
    {{ bin_oc }} adm release info \
      -a {{ config_pull_secret_file }} \
      --image-for='pod' "quay.io/openshift-release-dev/ocp-release:{{ config_cluster_version }}"
  environment: "{{ config_installer_environment | d(omit) }}"
  register: _cmd_release_info

- debug: var=_cmd_release_info

- ansible.builtin.set_fact:
    _cloud_provider_name: external
    _pod_image: "{{ _cmd_release_info.stdout }}"
    _mc_kubelet_workaround: ""

    # _mc_kubelet_workaround: >
    #   #KUBELET_PROVIDERID=$(curl -H "Authorization: Bearer Oracle" -sL http://169.254.169.254/opc/v2/instance/ | jq -r .id)

- name: Crete kubelet config
  ansible.builtin.template:
    src: patches/mc-kubelet.yaml.j2
    dest: "{{ config_install_dir }}/openshift/99_openshift-machineconfig_02-{{ _machine_config_role }}-kubelet.yaml"
    #dest: "/tmp/99_openshift-machineconfig_02-{{ _machine_config_role }}-kubelet.yaml"
  loop_control:
    loop_var: _machine_config_role
  loop:
  - master
  - worker
