---
_cluster_prefix: "{{ cluster_state.infra_id }}"

# Vars used on Bootstrap
bootstrap_bucket: "{{ _cluster_prefix }}-infra"

# Vars used on Machine/Compute Stack
_instance_type: "{{ bootstrap_instance | d('m6i.xlarge') }}"
_instance_profile: "{{ cluster_state.compute.iam_profile_bootstrap }}"
_image_id: "{{ custom_image_id | d(cluster_state.compute.image_id) }}"

_userdata_template: ocp-nodes-user-data.j2
openshift_userdata:
  config_source: "https://api-int.{{ cluster_state.dns.cluster_domain }}:22623/config/worker"
  ca_source: "{{ cluster_state.certificates.root_ca }}"

# Stack Compute (Ansible Role cloud_compute) options:
compute_resources:

  - provider: oci
    type: machine
    
    # cloud_compute role to discovery for OCI:
    image_name: "{{ custom_image_id }}"
    vnic_subnet_name: "{{ cluster_state.infra_id }}-net-private"
    network_security_group_names:
    - "{{ cluster_state.infra_id }}-nsg-compute"

    # OCI spec
    spec:
      state: present
      compartment_id: "{{ oci_compartment_id }}"
      display_name: "{{ cluster_state.infra_id }}-opct-01"
      region: "{{ config_cluster_region }}"
      #freeform_tags: {'Department': 'Finance'}
      #defined_tags: {'Operations': {'CostCenter': 'US'}}
      availability_domain: "gzqB:US-SANJOSE-1-AD-1"
      fault_domain: FAULT-DOMAIN-1

      # platform_config:
      #   type: AMD_VM
      shape: "VM.Standard.E4.Flex"
      shape_config:
        ocpus: 4
        memory_in_gbs: 8
      agent_config:
        are_all_plugins_disabled: true
    
      source_details:
        source_type: image

      create_vnic_details:
        display_name: "{{ cluster_state.infra_id }}-opct-01-vnic0"
        assign_public_ip: false
        assign_private_dns_record: true
        hostname_label: "opct-01"
      metadata:
        user_data: "{{ lookup('template', _userdata_template) | to_nice_json | string | b64encode }}"
